"""Safe runtime fallback ladder for LLM providers.

Contract:
  · Ladder is STRICTLY DOWNWARD IN COST: api → claude-cli → ollama.
    NEVER upward. A property test locks this invariant.
  · LLM_FALLBACK_ENABLED env, default TRUE (safe direction only —
    upward fallback isn't reachable regardless of flag).
  · Every fallback logs a WARNING and persists a row to
    llm_fallback_events so it surfaces in `morgoth session-report`.
    Silent fallback would poison every downstream measurement
    (theses generated by ollama while the operator believes claude-cli
    was in use would corrupt the model comparison).
"""

from __future__ import annotations

import os
from typing import Any, Callable, Awaitable

from loguru import logger

from core.llm.providers import Provider, HttpApiKeyMissing, HttpApiError

# Downward ladder ONLY. Any change here is a policy change — the test
# suite enforces that the resulting sequence is monotonically weakly-
# non-increasing in cost.
_LADDER: list[str] = ["api", "claude-cli", "ollama"]


def _rank(provider: str) -> int:
    """Cost rank. Higher = more expensive. Unknown providers return 0
    so they can never be a legal fallback target above a known one."""
    try:
        return len(_LADDER) - _LADDER.index(provider)
    except ValueError:
        return 0


def fallback_enabled() -> bool:
    """Default TRUE. Only the DOWNWARD ladder is reachable regardless
    (upward is structurally impossible), so a False here disables
    all cross-provider fallback."""
    raw = (os.environ.get("LLM_FALLBACK_ENABLED") or "true").strip().lower()
    return raw in ("1", "true", "on", "yes")


def _next_provider_down(current: str) -> str | None:
    """Return the next provider one rung DOWN from `current`, or None
    if we're already at the bottom (ollama)."""
    if current not in _LADDER:
        return None
    idx = _LADDER.index(current)
    if idx + 1 >= len(_LADDER):
        return None
    return _LADDER[idx + 1]


# In-process counter (per-run visibility even when the DB write fails).
# session-report reads from llm_fallback_events; this counter is a fast
# secondary signal.
_INPROC_FALLBACK_COUNT: dict[tuple[str, str, str], int] = {}


async def _log_fallback(
    pm: Any, task: str, configured: str, used: str, reason: str,
) -> None:
    """WARN + persist. Non-fatal on DB write failure."""
    logger.warning(
        "LLM FALLBACK: task={} configured={} used={} reason={}",
        task, configured, used, reason,
    )
    key = (task, configured, used)
    _INPROC_FALLBACK_COUNT[key] = _INPROC_FALLBACK_COUNT.get(key, 0) + 1
    if pm is None:
        return
    try:
        pool = pm._require_pool()
        async with pool.acquire() as conn:
            await conn.execute(
                "INSERT INTO llm_fallback_events (task, configured, used, reason) "
                "VALUES ($1, $2, $3, $4)",
                task, configured, used, reason[:500],
            )
    except Exception as exc:
        logger.warning("llm_fallback_events insert failed (non-fatal): {}", exc)


async def call_with_fallback(
    build_provider: Callable[[str], Provider | None],
    task: str,
    configured_provider: str,
    call: Callable[[Provider], Awaitable[str]],
    *,
    pm: Any = None,
) -> str:
    """Execute `call(provider)` with the configured provider; on
    provider-side failure, walk the ladder DOWNWARD to the first
    reachable alternative. `build_provider(name)` returns a Provider
    or None if unbuildable (e.g. api without key).

    LADDER STRICTLY DOWNWARD: from api ↓ claude-cli ↓ ollama. NEVER
    upward. Enforced by _next_provider_down which only walks forward
    in _LADDER.

    Errors that DO NOT trigger fallback:
      · The result payload being empty (that's the callee's problem).
      · A ValueError raised BEFORE the provider is even instantiated
        (bad config — surface it).
    """
    current = configured_provider
    tried: list[str] = []
    last_exc: Exception | None = None
    while current is not None:
        tried.append(current)
        provider = build_provider(current)
        if provider is None:
            last_exc = HttpApiKeyMissing(f"{current} unbuildable in this env")
            if fallback_enabled():
                current = _next_provider_down(current)
                if current is None:
                    break
                await _log_fallback(pm, task, configured_provider, current,
                                    f"{tried[-1]} unbuildable")
                continue
            raise last_exc
        try:
            return await call(provider)
        except (HttpApiKeyMissing, HttpApiError, RuntimeError, OSError) as exc:
            last_exc = exc
            if not fallback_enabled():
                raise
            nxt = _next_provider_down(current)
            if nxt is None:
                break
            await _log_fallback(pm, task, configured_provider, nxt,
                                f"{type(exc).__name__}: {str(exc)[:100]}")
            current = nxt
    # Ladder exhausted — surface the last exception (structured, not raised
    # arbitrary). The caller (brain._extract_theses etc.) already treats an
    # exception as "return []", so this preserves current cycle behaviour.
    raise last_exc if last_exc else RuntimeError(f"no fallback for task={task}")


def in_proc_fallback_count() -> int:
    """Total fallback events observed in this process — quick check for
    tests and the session-report fallback line."""
    return sum(_INPROC_FALLBACK_COUNT.values())
